services:
  komet:
    build:
      context: .
      dockerfile: docker/Dockerfile-komet-web
    container_name: komet
    ports:
      - "${KOMET_PORT:-80}:8080"

    volumes:
      - ~/Solor:/root/Solor
      - ./docker/komet-data/users.ini:/root/Solor/users.ini:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/status/alive"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rapidenv
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  komet-data:
    driver: bridge

networks:
  rapidenv:
    driver: bridge