services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - nexus-data:/nexus-data
    networks:
      - rapidenv
    restart: unless-stopped

  komet:
    build: ./
    container_name: komet
    ports:
      - "8080:8080"
    volumes:
      - ~/Solor:/root/Solor
    networks:
      - rapidenv
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nexus
      - komet
    networks:
      - rapidenv
    restart: always

volumes:
  nexus-data:
  komet-data:

networks:
  rapidenv:
    driver: bridge