services:
  komet:
    build:
      context: .
      dockerfile: docker/Dockerfile-komet-web
    container_name: komet
    volumes:
      - ~/Solor:/root/Solor
      - ./docker/komet-data/users.ini:/root/Solor/users.ini:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/status/alive"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rapidenv
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile-nginx
    container_name: nginx
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx-logs:/var/log/nginx
    depends_on:
      - komet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${NGINX_PORT:-80}/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rapidenv
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  komet-data:
  nginx-logs:
    driver: bridge

networks:
  rapidenv:
    driver: bridge