services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - nexus-data:/nexus-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rapidenv
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  komet:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: komet
    volumes:
      - ~/Solor:/root/Solor
      - ./docker/komet-data/users.ini:/root/Solor/users.ini:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status/alive"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rapidenv
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:1.26.3-alpine-slim
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx-logs:/var/log/nginx
    depends_on:
      - nexus
      - komet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rapidenv
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  nexus-data:
  komet-data:
  nginx-logs:
    driver: local

networks:
  rapidenv:
    driver: bridge