name: Build and Publish Komet App

on:

  push:
   tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:

      - name: Checkout komet repository code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
         context: .
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/komet:${{ github.ref_name }}