name: Build and Publish Komet App

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout komet repository code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile-komet-web
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/komet:${{ github.ref_name }}

      - name: Trigger Repository Dispatch
        run: |
            curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{secrets.IKMDEVOPS_PAT_TOKEN}}" \
            https://api.github.com/repos/ikmdev/ike-box/dispatches \
            -d '{"event_type":"ike-box-update","client_payload":{"version":"${{ github.ref_name }}"}}'
